// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWg60Umd-t1C_PVllIPEoAmM2bp60pTno',
    appId: '1:850326404723:web:252dd7d0686ed41897f406',
    messagingSenderId: '850326404723',
    projectId: 'khadija-firebase',
    authDomain: 'khadija-firebase.firebaseapp.com',
    storageBucket: 'khadija-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5_Q5bQMI_tRadJado4BRfDM88nTcoHTA',
    appId: '1:850326404723:android:739aeeafecbc8f8f97f406',
    messagingSenderId: '850326404723',
    projectId: 'khadija-firebase',
    storageBucket: 'khadija-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Eum7yqNkbt_FtL7jN_kawFpDabsMrPI',
    appId: '1:850326404723:ios:4f99e95b5ae3094b97f406',
    messagingSenderId: '850326404723',
    projectId: 'khadija-firebase',
    storageBucket: 'khadija-firebase.firebasestorage.app',
    iosBundleId: 'com.example.newwww',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Eum7yqNkbt_FtL7jN_kawFpDabsMrPI',
    appId: '1:850326404723:ios:4f99e95b5ae3094b97f406',
    messagingSenderId: '850326404723',
    projectId: 'khadija-firebase',
    storageBucket: 'khadija-firebase.firebasestorage.app',
    iosBundleId: 'com.example.newwww',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWg60Umd-t1C_PVllIPEoAmM2bp60pTno',
    appId: '1:850326404723:web:f9b8d8feecbe5ab797f406',
    messagingSenderId: '850326404723',
    projectId: 'khadija-firebase',
    authDomain: 'khadija-firebase.firebaseapp.com',
    storageBucket: 'khadija-firebase.firebasestorage.app',
  );
}
